apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
  labels:
    app.kubernetes.io/name: spark-history-server
    app.kubernetes.io/version: v2.4.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-history-server
      app.kubernetes.io/version: v2.4.5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spark-history-server
        app.kubernetes.io/version: v2.4.5
    spec:
      containers:
      - name: spark-history-server
        image: registry.cn-hangzhou.aliyuncs.com/zul/spark:v2.4.5
        args: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
          name: http
          protocol: TCP
        env:
        - name: SPARK_HISTORY_OPTS
          value: "-Dspark.history.fs.logDirectory=hdfs:///spark2-history/ -Dspark.history.ui.port=18080 -Dspark.history.provider=org.apache.spark.deploy.history.FsHistoryProvider"
        - name: HADOOP_USER_NAME
          value: "hdfs"
        - name: HADOOP_CONF_DIR
          value: "/etc/hadoop/conf"

        volumeMounts:
        - name: hadoop-config
          mountPath: /etc/hadoop/conf
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      dnsPolicy: ClusterFirst

      volumes:
      - name: hadoop-config
        configMap:
          name: hadoop-config
          items:
            - key: core-site.xml
              path: core-site.xml
            - key: hdfs-site.xml
              path: hdfs-site.xml

      - name: localtime
        hostPath:
          path: /etc/localtime